typography_spectrum: 0.07238
color:
  brandColors:
    - '#ffffff'
    - '#07060b'
    - '#363240'
    - '#e0ae00'
    - '#706979'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7189
analytics:
  google: null
  facebook: null
  twitter: null
name: Stevenson Grullon
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Director of Photography
description: Seamless Light
purpose: []
