name: stevenoiz
favicon: null
layout_spectrum: 0.9605272419285029
typography_spectrum: 0.83556
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffbf8'
    - '#fec430'
    - '#83b4ee'
    - '#0d0c12'
    - '#4d588b'
  brandStrength: 0.08101239334791899
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
